### ISSUE TITLE
Verbundkürzel: VBB

### ISSUE THREAD

**Issue by osm-ToniE** [mfdz/GTFS-Issues#112]
**Beschreibe die Ergänzung/Erweiterung des Feeds, die Du wünscht**
- Die GTFS-Daten sind unter einem 'permalink' verfügbar
- HEAD und "Last-Modified"  werden unterstützt

**Aktualisierungszeitpunkt der GTFS-Daten:**
./.

**Downloadlink der GTFS-Daten:**
https://www.vbb.de/fileadmin/user_upload/VBB/Dokumente/API-Datensaetze/gtfs-mastscharf/GTFS.zip

**Comment by derhuerst** [comment]
verwandt: https://github.com/mfdz/GTFS-Issues/issues/82

**Comment by hbruch** [comment]
@osm-ToniE die in #82 genannte URL http://vbb.de/vbbgtfs erfüllt diese Anforderungen, oder?

**Comment by osm-ToniE** [comment]
Ja, letztendlich landet man dann bei dem von mir angegebenen Link - durch mehrere 301 / 307 responses

toni@everest:~$ curl -sI http://vbb.de/vbbgtfs
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 23 Dec 2022 16:14:51 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://vbb.de/vbbgtfs

toni@everest:~$ curl -sI https://vbb.de/vbbgtfs
HTTP/2 301 
server: nginx
date: Fri, 23 Dec 2022 16:15:07 GMT
content-type: text/html
content-length: 162
location: https://www.vbb.de/vbbgtfs

toni@everest:~$ curl -sI https://www.vbb.de/vbbgtfs
HTTP/2 307 
server: nginx
date: Fri, 23 Dec 2022 16:15:37 GMT
content-type: text/html; charset=UTF-8
x-redirect-by: TYPO3 Redirect 2520
location: /fileadmin/user_upload/VBB/Dokumente/API-Datensaetze/gtfs-mastscharf/GTFS.zip

**Comment by osm-ToniE** [comment]
toni@everest:~$ curl -sI https://www.vbb.de/fileadmin/user_upload/VBB/Dokumente/API-Datensaetze/gtfs-mastscharf/GTFS.zip
HTTP/2 200 
server: nginx
date: Fri, 23 Dec 2022 16:18:59 GMT
content-type: application/zip
content-length: 67550333
last-modified: Fri, 23 Dec 2022 15:09:12 GMT
etag: "63a5c498-406bc7d"
accept-ranges: bytes

**Comment by hbruch** [comment]
Danke fürs Bestätigen. Ich schließe damit diesen Issue.
