### ISSUE TITLE
Rheinbahn Bus: Trip stops on Station exit (type 2)

### ISSUE THREAD

**Issue by taseroth** [mfdz/GTFS-Issues#119]
stops.txt contains the following stop:
```
grep 'de:05158:19054:1' stops.txt
"de:05158:19054:1","","Erkrath Nord Bf","Zugang","51.229261000000","6.909293000000",2,"de:05158:19054_G",0,"","2"
```
marking it as entry/exit (type '2')

stop_times.txt is using that stop:
```
grep 'de:05158:19054:1' stop_times.txt
2008084914,9:13:30,9:13:30,"de:05158:19054:1",38,0,0,""
2008084921,10:13:30,10:13:30,"de:05158:19054:1",38,0,0,""
2008084917,10:43:30,10:43:30,"de:05158:19054:1",38,0,0,""
2008084920,11:13:30,11:13:30,"de:05158:19054:1",38,0,0,""
2008084916,11:43:30,11:43:30,"de:05158:19054:1",38,0,0,""
2008084919,12:13:30,12:13:30,"de:05158:19054:1",38,0,0,""
2008084915,12:43:30,12:43:30,"de:05158:19054:1",38,0,0,""
2008084918,13:13:30,13:13:30,"de:05158:19054:1",38,0,0,""
2008084913,14:13:30,14:13:30,"de:05158:19054:1",38,0,0,""
2008084912,15:13:30,15:13:30,"de:05158:19054:1",38,0,0,""
2008084911,16:13:30,16:13:30,"de:05158:19054:1",38,0,0,""
2008084910,17:13:30,17:13:30,"de:05158:19054:1",38,0,0,""
2008084909,18:13:30,18:13:30,"de:05158:19054:1",38,0,0,""
```

The correct value I assume would be `'de:05158:19054_G'` 

Source: DELFI-Datensatz_GTFS_20230102

**Comment by hbruch** [comment]
Thanks for the issue report. I'll close this one, as it duplicates #72 which enumerates all stops with wrong types.  

Regarding the correct stop_id, I assume it should be `de:05158:19054:2:1`, `de:05158:19054:2:2` or `de:05158:19054:2:3`, which are bus quaies at Erkrath station. (stops with `_G` suffix are artifacts in DELFI's GTFS feed, which are not official stops according to the zHV (zentrales Haltestellenverzeichnis).
