### ISSUE TITLE
SaarVV: Falsche Position der Haltestelle Wahlen, Lehmbergstraße

### ISSUE THREAD

**Issue by marecabo** [mfdz/GTFS-Issues#132]
**Beschreibe den Fehler**
Die Bushaltestelle "Wahlen, Lehmbergstraße" des SaarVV hat eine falsche Position.

```csv
# stops.txt
stop_name,parent_station,stop_id,stop_lat,stop_lon
Wahlen, Lehmbergstraße,606500,49.487057,67.73103
```

Bei der Längengradangabe ist das Komma verrutscht, laut OSM ist 6.7731920 der richtige Wert.

**Referenz**
https://www.openstreetmap.org/node/1371136862

**Aktualisierungszeitpunkt der GTFS-Daten:**
Sun May 21 04:13:09 CEST 2023

**Downloadlink der GTFS-Daten:**
https://gtfs.de/de/feeds/de_full/ @ Sun May 21 04:13:09 CEST 2023
Basiert auf dem Netex Datensatz von DELFI

**Comment by fahrplaner** [comment]
Im aktuellen DELFI-Datensatz von https://www.opendata-oepnv.de ist folgender Datensatz enthalten: 

> "de:10042:24007::240071","","Lehmbergstr., Wahlen Losheim",,"49.486879000000","6.773311000000",0,,0,"",""

Auch bei gtfs.de sieht's besser aus:

> "Lehmbergstr., Wahlen Losheim",,29065,49.48695,6.773266,1
> "Wahlen, Lehmbergstraße",29065,361629,49.486877,6.773311,

**Comment by hbruch** [comment]
Danke für den Hinweis!

`de:10042:24007::240071` liegt schräg gegenüber der aktuell einzig in OSM erfassten `de:10042:24007::240076`:
<img width="418" alt="image" src="https://github.com/mfdz/GTFS-Issues/assets/2187389/5de92613-9427-4157-9604-33c6c74f3f3a">

Laut DELFI GTFS-Daten vom 25.03.2024 ist jedoch nur `de:10042:24007::240071` aktuell bedient durch Linie 225 in Richtung Römerstr. Wahlen Losheim/Schule Wahlen Losheim, was mir grundsätzlich plausibel scheint.

Ich schließe diesen Eintrag dennoch, da das ursprüngliche Problem korrigiert zu sein scheint.

Für OSM habe ich eine [Note](https://www.openstreetmap.org/note/4171513) erstellt.
