### ISSUE TITLE
VVS: Language Code(s) mit nicht empfohlener Großschreibung

### ISSUE THREAD

**Issue by derhuerst** [mfdz/GTFS-Issues#136]
Der VVS-Datensatz enthält den Wert `DE` für `agency.agency_lang`, dabei sollen diese idealerweise die richtige Großkleinschreibung (`de` bzw. `de-DE`) haben.

```csv
agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,ticketing_deep_link_id
"VVS","VVS","https://www.vvs.de","Europe/Berlin","DE","+49 711 19449","VVS_ticketing"
```

Dies sorgt in Tools (wie z.B. [`gtfs-via-postgres`](https://github.com/public-transport/gtfs-via-postgres)) für Verarbeitungsfehler, die nicht extra in eine einheitliche Großkleinschreibung umwandeln, sondern eine den Empfehlungen und Konventionen entsprechende Schreibung *erwarten*.

**Referenz**

GTFS definiert `agency.agency_lang` als *Language Code*, und [diesen wiederum wie folgt](https://gtfs.org/schedule/reference/#field-types):

> *Language code* – An IETF BCP 47 language code. For an introduction to IETF BCP 47, refer to http://www.rfc-editor.org/rfc/bcp/bcp47.txt and http://www.w3.org/International/articles/language-tags/. 
Example: `en` for English, `en-US` for American English or `de` for German.

BCP 47 empfiehlt (aber erzwingt nicht), die offizielle Großkleinschreibung zu verwenden:

> Although case distinctions do not carry meaning in language tags, consistent formatting and presentation of language tags will aid users. The format of subtags in the registry is RECOMMENDED as the form to use in language tags.  This format generally corresponds to the common conventions for the various ISO standards from which the subtags are derived.

**Aktualisierungszeitpunkt der GTFS-Daten:**

2023-09-08

**Downloadlink der GTFS-Daten:**

`https://download.vvs.de/gtfs_realtime.zip`

**Comment by maxkobaldVVS** [comment]
Hallo @derhuerst ,
wir haben das Language-Feld korrigiert und mit dem nächsten Datenexport sollte "de" ausgegeben werden. Wir hoffen, dass die Abnehmer das entsprechend flexibel konfiguriert haben und Anwendungen nicht darunter leiden.

Viele Grüße,
Max Kobald (VVS)

**Comment by 1Maxnet1** [comment]
> Hallo @derhuerst , wir haben das Language-Feld korrigiert und mit dem nächsten Datenexport sollte "de" ausgegeben werden. Wir hoffen, dass die Abnehmer das entsprechend flexibel konfiguriert haben und Anwendungen nicht darunter leiden.
> 
> Viele Grüße, Max Kobald (VVS)

Ich habe soeben mal den aktuellen Datensatz gecheckt und es ist "de" angegeben. @derhuerst m.E. kann das Issue geschlossen werden :)
