### ISSUE TITLE
[DB Navigator] Zwischenspeicherung des Nachnamens beim Import von Aufträgen

### ISSUE THREAD

**Issue by codedust** [mfdz/GTFS-Issues#138]
Dies ist kein Issue zu GTFS selbst, sondern zum DB Navigator. Ich konnte leider keinen Issue-Tracker für den DB Navigator finden. Vielleicht kennt ja hier einen solchen Tracker. Freue mich über Hinweise!

Falls diese Art von Issues hier unerwünscht ist, schließt dieses Issue gerne direkt wieder!

-----

Zum Issue: Beim manuellen Hinzufügen eines neuen Tickets mittels Auftragsnummer und Nachname (via "Meine Reisen" -> "+"-Button) wäre es extrem hilfreich, wenn der zuletzt eingegebene Nachname (ggf. optional) zwischengespeichert würde. Der DB Navigator kennt ohnehin schon meinen Nachnamen und nach Abruf des Tickets auch den im Ticket angegebenen (ggf. abweichenden) Nachnamen. Hier sollte es also kein Datenschutz und auch kein IT-Sicherheitsproblem geben, da der eigene Nachname ja wie beschrieben ohnehin bereits an anderer Stelle in der App angezeigt wird.

**Comment by hbruch** [comment]
Hi @codedust, 
wie Du schreibst, liegen Meldungen zum DB Navigator außerhalb des Fokus dieses Issues-Trackers. Ich schließe daher den Eintrag hier, werde aber mal bei DB anregen, dass sie je einen einrichten könnte. Nach meiner bisheringen Erfahrung ist die Erfolgswahrscheinlichkeit eher gering (unabhängig davon ob DB oder nicht).

Unabhängig davon: Hast Du das Feedback auch schon direkt an die DB gegeben?
