### ISSUE TITLE
DELFI (VMT, bodo,VGN): Busverkehre als Schienenverkehre angegeben

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#144]
**Beschreibe den Fehler**
Im aktuellen GTFS-Datensatz werden Busverkehre des VMT als Regionalzug (`route_type=106`) angegeben:

```sh
grep ,106, routes.txt

...
"de:VMT:16068009|Bus|111|111|EVAGBus:_106",11742,"111","",106,"54AB26","FFFFFF",""
"de:VMT:16062041|Bus|311|K|NDH_Bus:_106",13429,"K","",106,"","",""
"de:VMT:16062041|Bus|307|G|NDH_Bus:_106",13429,"G","",106,"","",""
"de:VMT:16062041|Bus|305|E|NDH_Bus:_106",13429,"E","",106,"","",""
"de:VMT:16062041|Bus|301|A|NDH_Bus:_106",13429,"A","",106,"","",""
"de:VMT:16062066|Bus|293|293|NDH_Bus:_106",13429,"293","",106,"","",""
"de:VMT:16062066|Bus|292|292|NDH_Bus:_106",13429,"292","",106,"","",""
"de:VMT:16065067|Bus|291|291|NDH_Bus:_106",13429,"291","",106,"","",""
"de:VMT:16062063|Bus|29|29|NDH_Bus:_106",13429,"29","",106,"","",""
"de:VMT:16062037|Bus|282|282|NDH_Bus:_106",13429,"282","",106,"","",""
"de:VMT:16062037|Bus|281|281|NDH_Bus:_106",13429,"281","",106,"","",""
"de:VMT:16062037|Bus|28|28|NDH_Bus:_106",13429,"28","",106,"","",""
"de:VMT:16061117|Bus|272|272|NDH_Bus:_106",13429,"272","",106,"","",""
"de:VMT:16062062|Bus|271|271|NDH_Bus:_106",13429,"271","",106,"","",""
"de:VMT:16061116|Bus|27|27|NDH_Bus:_106",13429,"27","",106,"","",""
"de:VMT:16062062|Bus|262|262|NDH_Bus:_106",13429,"262","",106,"","",""
"de:VMT:16062041|Bus|261|261|NDH_Bus:_106",13429,"261","",106,"","",""
"de:VMT:16062041|Bus|26|26|NDH_Bus:_106",13429,"26","",106,"","",""
"de:VMT:16062062|Bus|251|251|NDH_Bus:_106",13429,"251","",106,"","",""
"de:VMT:16062062|Bus|25|25|NDH_Bus:_106",13429,"25","",106,"","",""
"de:VMT:16062005|Bus|241|241|NDH_Bus:_106",13429,"241","",106,"","",""
"de:VMT:16062005|Bus|24|24|NDH_Bus:_106",13429,"24","",106,"","",""
"de:VMT:16062036|Bus|231|231|NDH_Bus:_106",13429,"231","",106,"","",""
"de:VMT:03153016|Bus|23|23|NDH_Bus:_106",13429,"23","",106,"","",""
"de:VMT:16062008|Bus|21|21|NDH_Bus:_106",13429,"21","",106,"","",""
"de:VMT:16062008|Bus|20|20|NDH_Bus:_106",13429,"20","",106,"","",""
...
```

**Aktualisierungszeitpunkt der GTFS-Daten**
22.04.2024

**Downloadlink der GTFS-Daten**
[Open-Data ÖPNV](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View)

**Comment by hbruch** [comment]
Ebenso sind mit dem o.g. Datensatz einige Buslinien des Busunternehmens [Schnappinger](https://www.schnappinger-reisen.de/), insbesondere im Landkreis Landsberg am Lech, fälschlicherweise als "railway service" (`route_type=100`) angegeben.

```sh
$ grep 13586 routes.txt | grep 100
"6135792_100",13586,"913","",100,"","",""
"6135791_100",13586,"912","",100,"","",""
"6135790_100",13586,"221","",100,"","",""
"6135789_100",13586,"141","",100,"","",""
"6135785_100",13586,"31","",100,"","",""
"6135784_100",13586,"22","",100,"","",""
"6135783_100",13586,"21","",100,"","",""
"6135782_100",13586,"14","",100,"","",""
```

**Comment by BeckertAnke** [comment]
Danke für den Hinweis. Sowohl für dem VMT als auch für Schnappinger sind die Verkehrsmittel korrigiert worden und sollten mit dem nächsten Datensatz korrekt als Bus kommen.

Anke Beckert (DELFI Wirkbetrieb)

**Comment by hbruch** [comment]
Danke für die schnelle Rückmeldung. Ich lasse den Eintrag noch offen, bis der nächste Datensatz bereitsteht.

**Comment by hbruch** [comment]
Im Datensatz vom 29.4.2024 sind weiterhin die folgenden zwei mutmaßlichen Buslinien des VMT als Regionalbahn (`route_type=106`) bzw. Straßenbahn (`route_type=900`)angegeben:

```
"de:VMT:16068009|Bus|111|111|EVAGBus:_106",11742,"111","",106,"54AB26","FFFFFF",""
"de:VMT:16068009|Bus|111|111|EVAGBus:_900",11742,"111","",900,"54AB26","FFFFFF",""
```

Darüberhinaus sind im aktuellen Datensatz diese beiden Linien des `VGN` als S-Bahnen (`route_type=109`) angegeben, obwohl es sich um Buslinien handeln dürfte:

```
"de:vgn:700_1874:0_109",14452,"1874","",109,"","",""
"de:vgn:700_1861:0_109",14452,"1861","",109,"","",""
```
Und auch bei diesen Linien des [Stadtverkehr Friedrichshafen](https://www.stadtverkehr-fn.de/) handelt es sich um Bus- und nicht wie angegeben S-Bahn-Linien:
```
"de:bodo:17SBF_:_109",14422,"SBF","",109,"","",""
"de:bodo:17E16_:_109",14422,"E16","",109,"","",""
"de:bodo:17011_:_109",14422,"11","",109,"","",""
"de:bodo:17010_:_109",14422,"10","",109,"","",""
"de:bodo:17005_:_109",14422,"5","",109,"","",""
"de:bodo:17002_:_109",14422,"2","",109,"","",""
"de:bodo:17001_:_109",14422,"1","",109,"","",""
```

**Comment by BeckertAnke** [comment]
Folgende Korrekturen sind im Datensatz vom 06.05. enthalten:
Die beiden VGN-Linien haben 'route_type=3'.
Die Linien vom Stadtverkehr Friedrichshafen haben 'route_type=700'

Leider noch nicht korrigiert werden konnten die Verkehrsmittel der Linie de:VMT:16068009|Bus|111|111|EVAGBus:
Ziel ist die Korrektur bis zur nächsten Woche.

Anke Beckert (DELFI Wirkbetrieb)

**Comment by hbruch** [comment]
Die gemeldeten Fehler sind im Datensatz vom 13.5.2024 behoben. Vielen Dank @BeckertAnke !
