### ISSUE TITLE
DELFI (VVO): Fehlende Daten im Kreis Meißen (14627)

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#150]
**Beschreibe den Fehler**
Im Kreis Meißen fehlen im aktuellen DELFI Datensatz 95% aller vor sechs Wochen noch gelieferten StopTimes.

**Auswertungen um das Problem aufzuzeigen**
Auswertung per `grep`:
```
$ grep  de:14627 gtfs-germany-2024-06-24/stop_times.txt | wc
    4848    4894  300874

$ grep  de:14627 gtfs-germany-2024-05-13/stop_times.txt | wc
   97352   97866 5779971
```

**Aktualisierungszeitpunkt der GTFS-Daten**
2024-06-24

**Downloadlink der GTFS-Daten**
[Open-Data ÖPNV](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View)

**Comment by CM-RMS** [comment]
Vielen Dank für den Hinweis - es gab ein Problem mit dem letzten Datenimport von diesem Lieferanten und in der nächsten Bereitstellung der GTFS-Daten sollten die Daten wieder enthalten sein.

**Comment by CM-RMS** [comment]
Es gibt eine Vielzahl an Prüfungen - aber bei der großen Anzahl an Daten die wir täglich bekommen kann so etwas leider immer mal passieren. Wir bauen die Prüfroutinen aber kontinuierlich aus und versuchen auch hier mehr zu automatisieren um die Qualität der Daten zu gewährleisten.

**Comment by derhuerst** [comment]
Als Hinweis: CalITP (das kalifornische Äquivalent zum DELFI) pflegt ein öffentliches Dashboard, in dem einige Metriken kontinuierlich & automatisiert errechnet werden, und mit Metriken der Vorgängerdatensätze verglichen werden, wie z.B. [für Bay Area Rapid Transit](https://reports.calitp.org/gtfs_schedule/2024/01/279/). Insbesondere die Darstellung von hinzugefügten, entfernten und geänderten IDs würde in diesem Fall helfen.

**Comment by hbruch** [comment]
Im Feed vom 8.7.2024 sind mit 94933 stop_times-Einträgen wieder annähernd so viele wie im Datensatz vom 13.5. enthalten.
