### ISSUE TITLE
DELFI (VAG): Linien der VAG fehlen in DELFI Feed

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#155]
**Beschreibe den Fehler**
Im GTFS Feed vom 30.09.2024 fehlen sämtliche Linien der "Agencies" `Bus Nürnberg`, `Tram Nürnberg`, `U-Bahn Nürnberg`, womit mutmaßlich die VAG Nürnberg gemeint ist (in Klammern: eine korrekte Angabe der Agency würde die Fehleranalyse und Kommunikation erleichtern).

**SQL um das Problem aufzuzeigen (falls zutreffend)**
Folgendes Statement listet die Anzahl der Linien je Agency, welche Haltestellen in Nürnberg (de:09564) bedienen:

```SQL
SELECT agency_name, count(*)
  FROM agency a
  JOIN routes r ON a.agency_id = r.agency_id
  WHERE route_id in (SELECT route_id
      FROM trips t
      JOIN stop_times st ON st.trip_id = t.trip_id
      WHERE stop_id like 'de:09564%')
  GROUP BY agency_name
  ORDER by agency_name
  ;
  
```
|                  agency_name                  | 23.09.2024 | 30.09.2024 |
|-----------------------------------------------|-------------|---|
| **Bus Nürnberg**                                  | 73           | **0** |
| Bus6                                          | 11           | 11 |
| DB Fernverkehr AG                             | 11           | 11 |
| DB Regio AG Bayern                            | 34           | 34 |
| Erlanger Stadtverkehr                         | 1            | 1 |
| Fahrplan 2022 Fürth                           | 2            | 2 |
| FlixBus-de                                    | 35           | 35 | 
| Go-Ahead Verkehrsgesellschaft Deutschland mbH | 1            | 1 |
| Nahreisezug                                   | 1            | 1 |
| Stadtverkehr Fürth                            | 5            | 5 |
| **Tram Nürnberg**                                 | 16           | **0** |
| **U-Bahn Nürnberg**                               | 3            | **0** |
| Österreichische Bundesbahnen                  | 4            | 4|

**Referenz**
Datensatz vom 23.09.2024

**Aktualisierungszeitpunkt der GTFS-Daten**
30.09.2024

**Downloadlink der GTFS-Daten**
[DELFI Datensatz](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View&tx_vrrkit_view%5Bdataset_formats%5D%5B0%5D=ZIP&tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&cHash=01414d5793fcd0abb0f3a2e35176752c)

**Comment by hbruch** [comment]
Nachtrag:

Weder in den aktuellen Hinweisen des Datensatzes vom 30.9.
<img width="435" alt="grafik" src="https://github.com/user-attachments/assets/8633cdb3-e196-49f2-befa-afaae235e148">

noch in den Hinweisen des Datensatzes vom 23.9. finden sich Hinweise zu einem Auslaufen bayrischer Lieferanten.

<img width="474" alt="grafik" src="https://github.com/user-attachments/assets/43f6b106-bbdf-468a-b25c-41573b13a131">

Die aktuellen Hinweise zur Qualitätsbeschreibung sind demnach so nicht aussagekräftig.

**Comment by hbruch** [comment]
Antwort der VAG:

> der Fehler ist bekannt und befindet sich gerade in der Fehleranalyse.
>  
> Das Problem war/ist, dass unser ITCS keine IST Daten liefert, sondern nur Soll-Daten.
>  
> Wir sind mit dem Hersteller in Verbindung und bereits bei der Fehlerbehebung.

**Comment by CM-RMS** [comment]
Wir stellen heute im laufe des Nachmittags einen neue GTFS Datensatz auf der DODP zur Verfügung. In diesem Datensatz werden die Solldaten des VAG Nürnberg wieder enthalten sein.

**Comment by hbruch** [comment]
Linien sind wieder verfügbar.
