### ISSUE TITLE
DELFI (Hameln): Linien der KVG Hameln fehlen 

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#156]
**Beschreibe den Fehler**
Im GTFS Feed vom 21.10.2024 fehlen sämtliche Linien der Agency `Kraftverkehrsgesellschaft Hameln mbH`.

**SQL um das Problem aufzuzeigen (falls zutreffend)**
Folgendes Statement listet die Anzahl der Linien je Agency, welche Haltestellen im Kreis Hameln-Pyrmont (de:03252) bedienen:

```SQL
SELECT agency_name, count(*)
  FROM agency a
  JOIN routes r ON a.agency_id = r.agency_id
  WHERE route_id in (SELECT route_id
      FROM trips t
      JOIN stop_times st ON st.trip_id = t.trip_id
      WHERE stop_id like 'de:03252%')
  GROUP BY agency_name
  ORDER by agency_name
  ;
  
```
|                  agency_name                  | count |
|-----------------------------------------------|-------------:|
| DivVgl/Waldorf1                         | 1            |
| Lippe3                                  | 6            |
| Lippe4                                  | 7            |
| RVHI Regionalverkehr Hildesheim GmbH    | 2            |
| RegioBus Hannover GmbH                  | 1            |
| Regionalbus Braunschweig GmbH           | 3            |
| Regionalverkehre Start Deutschland GmbH | 2            |
| S-Bahn Hannover                         | 2            |
| Schaumburger Verkehrs-Gesellschaft mbH  | 3            |

Im Datensatz vom 30.09.2024 waren darüberhinaus 50 Linien der Agency `Kraftverkehrsgesellschaft Hameln mbH` enthalten.

**Referenz**
Datensatz vom 30.09.2024

**Aktualisierungszeitpunkt der GTFS-Daten**
21.10.2024

**Downloadlink der GTFS-Daten**
[DELFI Datensatz](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View&tx_vrrkit_view%5Bdataset_formats%5D%5B0%5D=ZIP&tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&cHash=01414d5793fcd0abb0f3a2e35176752c)

**Comment by hbruch** [comment]
PS: Derzeit fehlen im Schnitt jeden Monat die Linien eines anderen Unternehmens im DELFI-GTFS-Feed. Die beigefügte Beschreibung enthält wieder keinen Hinweis auf die in dieser Lieferung fehlenden Linien.
Ich referenziere hier nochmals die Bitte umaussagekräftigere Begleitinformationen #152.

**Comment by CM-RMS** [comment]
Vielen Dank für den Hinweis - wir haben einen neuen GTFS Export bereitgestellt.

**Comment by hbruch** [comment]
Daten sind wieder enthalten. Danke.
