### ISSUE TITLE
NVBW: bitte Liste feedvalidator erweitern mit NVBW-Datensätzen

### ISSUE THREAD

**Issue by NVBWSeifert** [mfdz/GTFS-Issues#18]
Bitte auf der Seite https://gtfs.mfdz.de/ die fehlenden  Fahrplandatensätze der NVBW auflisten: 
* HNV (nur ohne Liniennetz)
* KVSH
* RBS
* RVS
* SBG
* SWEG
* SWHN
* TGO
* Tuticket
* VGC
* VGF
* VPE

**Aktualisierungszeitpunkt der GTFS-Daten:**
[05.09.2019]

**Downloadlink der GTFS-Daten:**
[https://www.nvbw.de/aufgaben/digitale-mobilitaet/fahrplandaten-mit-liniennetz/ ]

Danke für den Dienst!

**Comment by hbruch** [comment]
Wurden ergänzt.

Gib gerne Bescheid, wenn neue bereitgestellt werden oder RBS und HNV mit Liniennetz bereitstehen.
