### ISSUE TITLE
NVBW (DING): Doppelte service_id 

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#28]
**Beschreibe den Fehler**
Mehrere Service-IDs sind in calender.txt mehrfach vergeben. Dies macht den Feed unbrauchbar.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/2187389/76696836-10b76680-6690-11ea-99de-996cb3d2bd77.png">

**Aktualisierungszeitpunkt der GTFS-Daten:**
10.03.2020

**Downloadlink der GTFS-Daten:**
https://www.nvbw.de/fileadmin/nvbw/open-data/Fahrplandaten_mit_Liniennetz/ding.zip

**Comment by NVBWSeifert** [comment]
ein korrigierter Datensatz wurde heute mittag bereitgestellt und der vorhandenen Url

**Comment by hbruch** [comment]
Problem ist mit Datensatz vom 15.3.2020 behoben.
