### ISSUE TITLE
DELFI: agency_url nicht angegeben

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#30]
Nach GTFS API-Spezifikation ist das Feld agency_url der agency.txt verpflichtend anzugeben (required).

Für alle Einträge der agency.txt des Feeds ist die URL leer (""). Dies ist nach Standard nicht vorgesehen und führt bei einigen GTFS-Tools zu Verarbeitungsfehlern und Abbrüchen.

Aktualisierungszeitpunkt der GTFS-Daten:
1. April 2020

Downloadlink der GTFS-Daten:
https://cms.opendata-oepnv.de/fileadmin/datasets/delfi/20200401_fahrplaene_gesamtdeutschland_gtfs.zip

**Comment by hbruch** [comment]
Tritt in Datensatz mit Veröffentlichungszeitpunkt 3. April 2020 weiterhin auf.

**Comment by hbruch** [comment]
Antwort von DELFI e.V. am 6.4.:
> Da der DELFI-Datensatz im GTFS-Format ein eigenes DELFI-Produkt ist und als vollständiger Datensatz geliefert wird, bitten wir Sie bei der Weiterverwendung um Quellenangabe „DELFI e.V.“. Das Feld „agency url“ ist daher im DELFI-Datensatz nicht gefüllt.

**Comment by hbruch** [comment]
Die Quellenangabe kann auch direkt innerhalb des GTFS-Feeds in der seit einiger Zeit spezifizierten [attributions.txt](https://developers.google.com/transit/gtfs/reference#attributionstxt) ergänzt werden, so dass entsprechend vorbereitete Systeme diese automatisch korrekt anzeigen können. Unabhängig davon ist das Nichtfüllen des Feldes agency_url nicht konform zur Spezifikation und verursacht Fehler in verarbeitenden Systemen. Üblicherweise lösen Datenbereitsteller dies dadurch, dass sie die eigene URL (also z.B. https://www.delfi.de/) angegeben.

**Comment by hbruch** [comment]
Problem besteht im Datensatz vom 30.4.2020 weiterhin:
```sql
select agency_url, count(*) from gtfs.agency group by agency_url;
      agency_url       | count
-----------------------+-------
                       |   858
 www.von-rahden.de     |     1
 https://www.delfi.de/ |     1
```

**Comment by hbruch** [comment]
Problem besteht in Datensatz vom 08.05.2020 weiterhin:
```sql
select agency_url, count(*) from gtfs.agency group by agency_url;
      agency_url       | count
-----------------------+-------
                       |   822
 www.von-rahden.de     |     1
 https://www.delfi.de/ |     1
(3 rows)
```

**Comment by hbruch** [comment]
Für die meisten agencies ist Stand heute `https://www.delfi.de/` als agency angegeben.

Im Datensatz vom 26.11.2021 jedoch für die folgenden Eintrag nicht:
```
13426,"Karlsruher Verkehrsberbund","","Europe/Berlin","",""
13451,"ARGE SFB","","Europe/Berlin","",""
13452,"Frölich Linie","","Europe/Berlin","",""
13601,"Stadtbus Bad Wildungen","","Europe/Berlin","",""
```

Zudem ist die Schreibweise ist des KVV fehlerhaft (Verkehrs**b**erbund)

Um sicherzustellen, dass GTFS-Veröffentlichungen des DELFI e.V. den GTFS-Spezifikation entsprechen, empfehle ich den Einsatz eines Validators, z.B. [GTFSVTOR](https://github.com/mecatran/gtfsvtor) oder [MobilityData-GTFS-Validator](https://github.com/MobilityData/gtfs-validator)

**Comment by delfi-fahrplandaten** [comment]
Vielen Dank für den Hinweis. In den Daten vom 03.12. sind die URLs vollständig hinterlegt. 
Der Rechtschreibfehler wurde leider für heute vergessen zu korrigieren. Das ist dann in der nächsten Bereitstellung korrigiert.

**Comment by derhuerst** [comment]
Mit dem Datensatz vom 21.03.2022 enthalten zwar alle agencies eine `agency_url`, allerdings wird empfohlen,
- für die agencies ihre jeweiligen Websites als `agency_url`s zu verwenden,
- und für die den Feed erstellende Organisation die Felder `feed_publisher_url` bzw. `feed_contact_url ` in [`feed_info.txt`](https://gtfs.org/reference/static/#feed_infotxt) zu verwenden.

Darüber hinaus gilt [der Hinweis zuvor](https://github.com/mfdz/GTFS-Issues/issues/30#issuecomment-610452316) bzgl. [`attributions.txt`](https://gtfs.org/reference/static/#attributionstxt), mit der sich sehr detailliert ausdrücken lässt, von wem welche Daten stammen:


> Die Quellenangabe kann auch direkt innerhalb des GTFS-Feeds in der seit einiger Zeit spezifizierten [attributions.txt](https://developers.google.com/transit/gtfs/reference#attributionstxt) ergänzt werden, so dass entsprechend vorbereitete Systeme diese automatisch korrekt anzeigen können. Unabhängig davon ist das Nichtfüllen des Feldes agency_url nicht konform zur Spezifikation und verursacht Fehler in verarbeitenden Systemen. Üblicherweise lösen Datenbereitsteller dies dadurch, dass sie die eigene URL (also z.B. https://www.delfi.de/) angegeben.

**Comment by derhuerst** [comment]
Mit dem neuesten Datensatz vom 8.4. (`Last-Modified: Mon, 08 Apr 2024 11:02:27 GMT`) enthalten 3 Einträge wieder keine `agency_url`.

```shell
qsv search -s agency_url '^$' agency.txt
# agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
# 14582,Sonstige Eisenbahnen1,,Europe/Berlin,,
# 14587,AK Autokraft Projekt Smile24,,Europe/Berlin,,
# 14588,Omnibusverkehr Fischer,,Europe/Berlin,,
```

Wann stellt der DELFI endlich durch automatisierte Überprüfungen der eingehenden und ausgehenden Daten sicher, das Fehler nicht wiederholt passieren, die seit Jahren bekannt sind?

**Comment by hbruch** [comment]
Im Datensatz vom 12.08.2024 enthalten alle 1154 Agencies die `agency_url` `https://www.delfi.de`:

```sql
select agency_url, count(*) from gtfs.agency group by agency_url;
┌──────────────────────┬──────────────┐
│      agency_url      │ count_star() │
│       varchar        │    int64     │
├──────────────────────┼──────────────┤
│ https://www.delfi.de │         1154 │
└──────────────────────┴──────────────┘
```

Auch wenn für die Agencies sinnvollerweise die tatsächlich ihnen zugehörigen URLs eingetragen sein sollten, schließe ich den Eintrag, da derzeit immerhin kein syntaktischer Fehler mehr vorliegt.
