### ISSUE TITLE
VVS: shapes.txt nicht mehr in vvs_gfs.zip enthalten

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#4]
In den aktuellen, über openvvs bereitgestellten GTFS-Daten fehlt die früher bereits enthaltene shapes.txt.

Diese ist zwar nach GTFS-Standard optional und erhöht signifikant die Datei-Größe, jedoch sind in der Karte detailliert dargestellte Linienverläufe deutlich ansprechender. 

**Aktualisierungszeitpunkt der GTFS-Daten:**
4. Januar 2019, 08:24 (UTC+01:00)

**Comment by hbruch** [comment]
Nach Auskunft der VVS dürfen aktuell aus lizenzrechtlichen Gründen keine Shapes veröffentlicht werden. 
Nach der für Frühjahr 2019 geplanten Umstellung auf OpenStreetMap könnten die Shapes wieder bereitgestellt werden.

**Comment by frankgerhardt** [comment]
![image](https://user-images.githubusercontent.com/550621/50954095-c21fa280-14b5-11e9-9db7-f0cf4db48fd7.png)

Ich hätte erwartet, dass die blaue Linie am Anfang und Ende fortgesetzt wird und den Linienverlauf der U-Bahn zeigt.

**Comment by hbruch** [comment]
Workaround: Unter http://gtfs.mfdz.de/gtfs haben wir unter mittels [pfaedle](https://github.com/ad-freiburg/pfaedle) und OSM um shapes angereicherte GTFS Feeds bereitgestellt.

**Comment by hbruch** [comment]
Aktueller GTFS-Feed enthält immer noch keine Shapes, obwohl VVS seit einigen Monaten auf OSM umgestellt hat. Wir fragen daher direkt opendata bei vvs.de an:

> Sehr geehrte Damen und Herren,
> 
> der VVS hat seit einiger Zeit auf OpenStreetMap-Daten umgestellt. Seinerzeit wurde uns dies als Voraussetzung für eine erneute Veröffentlichung der mit Shapes angereicherten GTFS-Daten genannt.
> Ist absehbar, wann der VVS die GTFS-Daten wieder mit angereicherten Shapes bereitstellt?
> 
> Wir veröffentlichen diese Anfrage unter https://github.com/mfdz/GTFS-Issues/issues/4. Dort veröffentlichen wir auch gerne Ihre Antwort, falls Sie nicht direkt dort antworten möchten. 
> 
> Mit freundlichen Grüßen
> Holger Bruch

**Comment by hbruch** [comment]
Seit geraumer Zeit liefert VVS nun auch wieder shapes mit den GTFS-Daten aus. Mit 180MB ist diese shapes.txt doppelt so groß wie die von MFDZ mittels pfaedle generierten, könnte also wahrscheinlich nochmals deutlich kompakter werden. 

Der Vergleich zwischen VVS und pfaedle-shapes lässt erkennen, wo pfaedle mit der aktuellen Standardkonfiguration nicht exakt den offiziellen Verlauf abbildet:

"Abkürzungen":
<img width="420" alt="grafik" src="https://user-images.githubusercontent.com/2187389/122630401-90b65280-d0c3-11eb-9e21-c4fa7d5e33c6.png">

"Start nicht an stop Position"
<img width="573" alt="grafik" src="https://user-images.githubusercontent.com/2187389/122630420-c5c2a500-d0c3-11eb-85b4-01d6e7ebb116.png">

Ich schließe diesen Issue daher. Nutzende des VVS-Feeds sollten wieder die offiziellen Shapes - ggfs. größenreduziert mit z.B. [gtfstidy](https://github.com/patrickbr/gtfstidy) - nutzen
