### ISSUE TITLE
DELFI: Fehlerhafte shape Koordinaten

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#49]
147 Shape-Koordinaten liegen außerhalb des gültigen Bereichs.

```sql
SELECT COUNT(*)
   FROM gtfs.shapes
  WHERE NOT shape_pt_lon BETWEEN -180 AND 180
     OR NOT shape_pt_lat BETWEEN -90 AND 90;
 count
-------
   147
```

**Aktualisierungszeitpunkt der GTFS-Daten:**
15.05.2020

**Downloadlink der GTFS-Daten:**
https://cms.opendata-oepnv.de/fileadmin/datasets/delfi/20200515_fahrplaene_gesamtdeutschland_gtfs.zip

**Comment by derhuerst** [comment]
Mit dem DELFI-Datensatz vom 21.03.2022 und [`gtfs-via-postgres`](https://www.npmjs.com/package/gtfs-via-postgres):

```sql
SELECT COUNT(*)
FROM shapes
WHERE NOT st_x(shape_pt_loc::geometry) BETWEEN -180 AND 180
OR NOT st_y(shape_pt_loc::geometry) BETWEEN -90 AND 90
-- count
-- 0
```

**Comment by hbruch** [comment]
Danke. Ich schließe dann diesen Issue.
