### ISSUE TITLE
NVBW (Alle): Response liefert last-modified Header 

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#52]
**Art der Abweichung**
Nach Umstellung der GTFS-Download-Links liefert die HTTP-Response keinen last-modified header o.ä., womit auf abrufender Seite erkannt werden könnte, dass sich die Daten nicht geändert haben und kein erneuter Download erforderlich ist:
<img width="882" alt="grafik" src="https://user-images.githubusercontent.com/2187389/93659917-4a579880-fa4a-11ea-985c-57c2286cbbb9.png">

**Referenz**

> The web-server hosting GTFS data should be configured to correctly report the file modification date (see HTTP/1.1 - Request for Comments 2616, under Section 14.29).

Quelle: https://gtfs.org/best-practices/#dataset-publishing--general-practices

**Downloadlink der GTFS-Daten:**
z.B. https://www.nvbw.de/index.php?eID=dumpFile&t=f&f=317&token=29a8256cd6f7fc205c0c0470da7e376fa2da4979

**Comment by NVBWSeifert** [comment]
Danke für den Hinweis, das war uns leider selbst nicht aufgefallen.
Wir bemühen uns zeitnah um die Beseitigung des Problems

**Comment by hbruch** [comment]
Responses der Download-Links auf https://www.nvbw.de/open-data/fahrplandaten/fahrplandaten-mit-liniennetz verfügen mittlerweile wieder über last-modified Header
