### ISSUE TITLE
NVBW (SPNV): Zip-File korrupt 

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#53]
**Beschreibe den Fehler**
Das auf Seite https://www.nvbw.de/open-data/fahrplandaten/fahrplandaten-mit-liniennetz referenzierte SPNV-Zip-File mit URL https://www.nvbw.de/index.php?eID=dumpFile&t=f&f=374&token=d00497a5b8642cdb885d65f8a3a6d5d801f383a7 ist korrupt.

Die Generierung, Nutzung und Veröffentlichung von z.B. MD5 Prüfsummen reduziert die Wahrscheinlichkeit von Übertragungsfehlern.

**Aktualisierungszeitpunkt der GTFS-Daten:**
Unklar

**Downloadlink der GTFS-Daten:**
https://www.nvbw.de/index.php?eID=dumpFile&t=f&f=374&token=d00497a5b8642cdb885d65f8a3a6d5d801f383a7

**Comment by NVBWSeifert** [comment]
Wir bemühen uns um die zeitnahe Bereitstellung eines neuen, downloadfähigen Datensatzes

**Comment by hbruch** [comment]
File ist seit längerem wieder vollständig
