### ISSUE TITLE
VVS: Fehlender SEV RB60E

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#67]
Derzeit ist die Ammertalbahn gesperrt [1] und ihre Fahrten fehlen richtigerweise in den GTFS Daten.

Allerdings fehlt auch der in der VVS-Auskunft gelistete Schienenersatzverkehr (RB60E) [2] in den gestern bereitgestellten GTFS-Daten (Aktualisierung unter OpenVVS gestern, 25.5., 6:11)

Damit zeigen somit stadtnavi und Google für Abfragen der Verbindung Herrenberg-Tübingen derzeit einen größeren Umweg (Dauer > 1h) vs ca. 30 Minuten mit dem SEV an.

Da die Daten in der VVS-Auskunft abfragbar sind, scheinen die Daten dem VVS grndsätzlich vorzuliegen. Da der Datensatz vom 25.5.2021 datiert, sollte es sich auch nicht um ein Aktualitätsproblem der GTFS-Daten handeln.

**Referenz**
[VVS-Abfrage](https://www3.vvs.de/mng/#!/XSLT_TRIP_REQUEST2@result?language=de&deeplink=%7B%22dateTime%22:%7B%22date%22:%2226.05.2021%22,%22dateFormat%22:%22%22,%22time%22:%2207:05%22,%22timeFormat%22:%22%22,%22useRealTime%22:true,%22isDeparture%22:true%7D,%22via%22:%7B%22optionsList%22:%5B%5D,%22optionsListItem%22:%7B%22type%22:%22any%22,%22dwellTime%22:%220%22,%22enabled%22:true%7D%7D,%22efaParams%22:%7B%22illumTransfer%22:%22on%22,%22itOptionsActive%22:%221%22,%22language%22:%22de%22,%22locationServerActive%22:%221%22,%22noElevationProfile%22:%221%22,%22noElevationSummary%22:%221%22,%22outputOptionsActive%22:%221%22,%22securityOptionsActive%22:%221%22,%22useElevationData%22:%221%22,%22useRealtime%22:%221%22,%22tryToFindLocalityStops%22:%221%22,%22w_objPrefAl%22:%2212%22,%22w_regPrefAm%22:%221%22,%22searchLimitMinutes%22:%22360%22%7D,%22odvs%22:%7B%22orig%22:%22de:08115:4512%22,%22dest%22:%225021000%22%7D%7D)

**Aktualisierungszeitpunkt der GTFS-Daten:**
25.05.2021

**Downloadlink der GTFS-Daten:**
https://www.openvvs.de/dataset/e66f03e4-79f2-41d0-90f1-166ca609e491/resource/bfbb59c7-767c-4bca-bbb2-d8d32a3e0378/download/google_transit.zip

**Comment by AnkeBeckert** [comment]
Hallo Herr Bruch,

vielen Dank für den Hinweis.
Wir haben die GTFS-Exportkonfiguration angepasst. Im nächsten Datensatz (Veröffentlichung am 01.06. im Open Data Portal) sollten die Daten des SEV der Ammertalbahn mit drin sein.

Mit freundlichen Grüßen
Anke Beckert
Abteilung Fahrgastinformation
Verkehrs- und Tarifverbund Stuttgart GmbH (VVS)
Rotebühlstraße 121, 70178 Stuttgart
Telefon +49 711 6606-2130
***@***.******@***.***> | www.vvs.de<http://www.vvs.de/>
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart HRB 7357
Geschäftsführer: Thomas Hachenberger, Horst Stammler
Vorsitzender des Aufsichtsrates: Oberbürgermeister Dr. Frank Nopper



Von: Holger Bruch ***@***.***>
Gesendet: Mittwoch, 26. Mai 2021 08:21
An: mfdz/GTFS-Issues ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mfdz/GTFS-Issues] VVS: Fehlender SEV RB60E (#67)


Derzeit ist die Ammertalbahn gesperrt [1] und ihre Fahrten fehlen richtigerweise in den GTFS Daten.

Allerdings fehlt auch der in der VVS-Auskunft gelistete Schienenersatzverkehr (RB60E) [2] in den gestern bereitgestellten GTFS-Daten (Aktualisierung unter OpenVVS gestern, 25.5., 6:11)

Damit zeigen somit stadtnavi und Google für Abfragen der Verbindung Herrenberg-Tübingen derzeit einen größeren Umweg (Dauer > 1h) vs ca. 30 Minuten mit dem SEV an.

Da die Daten in der VVS-Auskunft abfragbar sind, scheinen die Daten dem VVS grndsätzlich vorzuliegen. Da der Datensatz vom 25.5.2021 datiert, sollte es sich auch nicht um ein Aktualitätsproblem der GTFS-Daten handeln.

Referenz
***@***.***?language=de&deeplink=%7B%22dateTime%22:%7B%22date%22:%2226.05.2021%22,%22dateFormat%22:%22%22,%22time%22:%2207:05%22,%22timeFormat%22:%22%22,%22useRealTime%22:true,%22isDeparture%22:true%7D,%22via%22:%7B%22optionsList%22:%5B%5D,%22optionsListItem%22:%7B%22type%22:%22any%22,%22dwellTime%22:%220%22,%22enabled%22:true%7D%7D,%22efaParams%22:%7B%22illumTransfer%22:%22on%22,%22itOptionsActive%22:%221%22,%22language%22:%22de%22,%22locationServerActive%22:%221%22,%22noElevationProfile%22:%221%22,%22noElevationSummary%22:%221%22,%22outputOptionsActive%22:%221%22,%22securityOptionsActive%22:%221%22,%22useElevationData%22:%221%22,%22useRealtime%22:%221%22,%22tryToFindLocalityStops%22:%221%22,%22w_objPrefAl%22:%2212%22,%22w_regPrefAm%22:%221%22,%22searchLimitMinutes%22:%22360%22%7D,%22odvs%22:%7B%22orig%22:%22de:08115:4512%22,%22dest%22:%225021000%22%7D%7D>

Aktualisierungszeitpunkt der GTFS-Daten:
25.05.2021

Downloadlink der GTFS-Daten:
https://www.openvvs.de/dataset/e66f03e4-79f2-41d0-90f1-166ca609e491/resource/bfbb59c7-767c-4bca-bbb2-d8d32a3e0378/download/google_transit.zip

-

**Comment by hbruch** [comment]
Vielen Dank, Frau Beckert! Aktualisierter GTFS-Feed vom 31. Mai 2021, 08:41 (UTC+02:00) enthält den RB60E.
