### ISSUE TITLE
DELFI: Falsche Bushaltestelle im Bus 753 von Herrenberg nach Rohrau

### ISSUE THREAD

**Issue by atomicbomberman** [mfdz/GTFS-Issues#68]
**Beschreibe den Fehler**
Die Route für den Bus 753 von "Herrenberg" nach "Rohrau Rathaus" enthält die Haltestelle "Stuttgart Untertürkheim". Diese Haltestelle wird vom Bus aber nicht angefahren. Sie ist auch viel zu weit entfernt so dass auch die Zeit dazu gar nicht passt.

**Referenz**
Eins der Trips (stop_times.txt), es gibt mehrere davon:
```
1445420408,13:53:00,13:53:00,"de:08115:4512:5:B_G",0,0,0,""
1445420408,13:55:00,13:55:00,"de:08115:4739:0:3_G",1,0,0,""
1445420408,13:56:00,13:56:00,"de:08115:7054:0:4_G",2,0,0,""
1445420408,13:57:00,13:57:00,"de:08115:7009:0:3_G",3,0,0,""
1445420408,13:59:00,13:59:00,"de:08115:4737:0:4_G",4,0,0,""      <-------- "Herrenberg Polizeihochschule"
1445420408,14:02:00,14:02:00,"de:08115:4736:0:4_G",5,0,0,""      <-------- "Stuttgart Untertürkheim"
1445420408,14:04:00,14:04:00,"de:08115:4735:1:4_G",6,0,0,""
1445420408,14:06:00,14:06:00,"de:08115:6479:0:3_G",7,0,0,""
1445420408,14:08:00,14:08:00,"de:08115:6483:0:4_G",8,0,0,""
1445420408,14:09:00,14:09:00,"de:08115:7073:0:4_G_G",9,0,0,""
1445420408,14:10:00,14:10:00,"de:08115:7053:0:4_G_G",10,0,0,""
1445420408,14:12:00,14:12:00,"de:08115:7052:0:4_G_G",11,0,0,""
1445420408,14:13:00,14:13:00,"de:08115:4727:1:4_G_G",12,0,0,""
1445420408,14:15:00,14:15:00,"de:08115:5774:3:3_G_G",13,0,0,""
1445420408,14:17:00,14:17:00,"de:08115:7152:0:4_G",14,0,0,""
1445420408,14:20:00,14:20:00,"de:08115:4729:0:3_G",15,0,0,""
```
stops.txt:
```
"de:08115:4737:0:4_G","","Herrenberg Polizeihochschule",,"48.609020000000","8.878762000000",0,,0,""
"de:08115:4736:0:4_G","","Stuttgart Untertürkheim",,"48.779847000000","9.250467000000",0,,0,""
```

**Aktualisierungszeitpunkt der GTFS-Daten:**
Die Daten wurden vor ca. 2 Wochen heruntergeladen.

**Comment by NVBWSeifert** [comment]
Bitte nochmal die stops.txt prüfen. Ich habe eben den DELFI GTFS-Datensatz heruntergeladen und dort ist korrekt
`"de:08115:4736:0:4_G","","Nufringen Kuppinger Str.",,"48.620548000000","8.887212000000",0,,0,""`
und das passt für den Linienverlauf

**Comment by hbruch** [comment]
Habe eben im Datensatz vom 27.8.2021 geprüft und dort ist ebenfalls korrekt die Kuppinger Straße angegeben:
```
$ grep "de:08115:4736:0:4_G" stops.txt
"de:08115:4736:0:4_G","","Nufringen Kuppinger Str.",,"48.620548000000","8.887212000000",0,,0,"",""
```
Ich schließe daher diesen Issue. @atomicbomberman, sollte das Problem aus Deiner Sicht weiterhin bestehen, öffne den Issue gerne mit konkreter Versionsangabe.
