### ISSUE TITLE
DELFI: Fehlende stop_id in stop_times.txt 

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#71]
**Beschreibe den Fehler**
stop_times.txt enthält Einträge ohne die Pflichtangabe stop_id:

```
1484745828,0:59:00,0:59:00,"",0,0,0,""
1484745828,1:12:00,1:12:00,"",1,0,0,""
1484745828,1:16:00,1:16:00,"",2,0,0,""
1484745828,1:19:00,1:19:00,"",3,0,0,""
1484745828,1:22:00,1:22:00,"",4,0,0,""
1484745828,1:31:00,1:31:00,"",5,0,0,""
1484745828,1:41:00,1:41:00,"",6,0,0,""
1484745828,1:47:00,1:47:00,"",7,0,0,""
1484745828,1:57:00,1:57:00,"",8,0,0,""
```

**Referenz**
https://developers.google.com/transit/gtfs/reference/#stop_timestxt

**Aktualisierungszeitpunkt der GTFS-Daten:**
27.08.2021

**Downloadlink der GTFS-Daten:**
https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Bdataset_formats%5D%5B0%5D=ZIP&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View

**Comment by delfi-fahrplandaten** [comment]
Der Fehler ist bekannt und an unserer Softwarehaus weitergeleitet. Datentechnisch kann ich aktuell nicht erkennen, was die Ursache sein könnte.

**Comment by derhuerst** [comment]
Mit dem DELFI-Datensatz vom 21.03.2022 erhalte ich keine solcher `stop_times.txt`-Zeilen:

```shell
qsv search -s stop_id '^$' stop_times.txt
# trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,stop_headsign
```

**Comment by hbruch** [comment]
Danke. Ich schließe diesen Eintrag.
