### ISSUE TITLE
DELFI: transfers.txt enthält undefinierte stop-IDs

### ISSUE THREAD

**Issue by derhuerst** [mfdz/GTFS-Issues#81]
`transfers.txt` enthält stop-IDs in `from_stop_id` & `to_stop_id`, die nicht in `stops.txt` definiert sind:

```shell
xsv join --left from_stop_id transfers.txt stop_id stops.txt | xsv search -s stop_id '^$' | xsv select 1-8
# from_stop_id,to_stop_id,transfer_type,min_transfer_time,from_route_id,to_route_id,from_trip_id,to_trip_id
# 000300164014,de:11000:900029101_G,2,360,,,,
# 000300164016,de:11000:900029101_G,2,360,,,,
xsv join --left to_stop_id transfers.txt stop_id stops.txt | xsv search -s stop_id '^$' | xsv select 1-8
# from_stop_id,to_stop_id,transfer_type,min_transfer_time,from_route_id,to_route_id,from_trip_id,to_trip_id
# de:11000:900029101_G,000300164014,2,360,,,,
# de:11000:900029101_G,000300164016,2,360,,,,
```

Aus dem [`transfers.txt`-Spec](https://gtfs.org/reference/static/#transferstxt):

> `from_stop_id`, ID referencing `stops.stop_id`, Required [...]
> `to_stop_id`, ID referencing `stops.stop_id`, Required [...]

**Aktualisierungszeitpunkt der GTFS-Daten:**

Ich nutze den DELFI-Datensatz vom 12.11.21:

```shell
shasum gtfs-germany.zip
# 9fa29949bca105d133b8fbc464edc250ad51fdfa  gtfs-germany.zip
```

```
       480 Nov 19 09:47 ./
      1920 Nov 19 09:47 ../
    184748 Nov 12 11:56 Beschreibung_DELFI-Datensatz_GTFS_20211112.pdf
     79860 Nov 12 14:22 agency.txt
    274198 Nov 12 14:22 calendar.txt
    917198 Nov 12 14:22 calendar_dates.txt
        64 Nov 12 14:22 frequencies.txt
       110 Nov 12 14:22 levels.txt
  21576510 Nov 12 14:22 pathways.txt
    991409 Nov 12 14:22 routes.txt
 247324824 Nov 12 14:22 shapes.txt
1958729470 Nov 12 14:22 stop_times.txt
  49301878 Nov 12 14:22 stops.txt
  51344806 Nov 12 14:22 transfers.txt
 107676619 Nov 12 14:22 trips.txt
```

**Downloadlink der GTFS-Daten:**

https://de.data.public-transport.earth/gtfs-germany.zip

**Comment by delfi-fahrplandaten** [comment]
Hallo,
das ist leider ein bekanntes Problem. Wir haben die Tage ein Update unseres Exports bekommen. Dieser ist noch in der Abnahmephase bei uns. Aber damit sollte das Problem der unbekannten stop_ids hoffentlich behoben sein.

**Comment by derhuerst** [comment]
Gibt es automatisierte Vorkehrungen, wie etwa ein Validierungs-Script, die sicherstellen, dass dieser Fehler nicht wieder auftritt?

**Comment by hbruch** [comment]
Problem besteht bei Datensatz vom 26.11.2021 weiterhin.

**Comment by delfi-fahrplandaten** [comment]
Ja. Das neue Release ist weiterhin nicht für die Produktion freigegeben.

**Comment by derhuerst** [comment]
Mit dem DELFI-Datensatz vom 21.03.2022 erhalte ich keine solcher Zeilen mehr:

```shell
shasum gtfs-germany.zip
# eed05c34821e65205acbd3f05f9b0b4dde746a6e  gtfs-germany.zip

qsv join --left from_stop_id transfers.txt stop_id stops.txt | qsv search -s stop_id '^$' | qsv select 1-8
# from_stop_id,to_stop_id,transfer_type,min_transfer_time,from_route_id,to_route_id,from_trip_id,to_trip_id
qsv join --left to_stop_id transfers.txt stop_id stops.txt | qsv search -s stop_id '^$' | qsv select 1-8
# from_stop_id,to_stop_id,transfer_type,min_transfer_time,from_route_id,to_route_id,from_trip_id,to_trip_id
```

**Comment by hbruch** [comment]
Fehler scheint behoben

**Comment by w-flo** [comment]
Ich hab die DELFI-GTFS vom 15.11.2025 und da passt wohl aktuell wieder was nicht. Die Stop-ID `"de:06412:11511:91:91"` ist 4x in transfers.txt enthalten, aber nicht in stops.txt.

**Comment by derhuerst** [comment]
vermutlich relevant: https://github.com/mfdz/GTFS-Issues/issues/180

**Comment by w-flo** [comment]
Zwei der Transfers mit der genannten (und in stops.txt weiterhin nicht enthaltenen) Stop-ID sind in 2025-12-15 nicht mehr enthalten, aber zwei sind noch übrig.

```
$ grep "de:06412:11511:91:91\"" transfers.txt 
"de:06412:2932","de:06412:11511:91:91",2,600,,,,
"de:06412:11511:91:91","de:06412:2932",2,600,,,,
```

**Comment by BeckertAnke** [comment]
Ich habe in den an uns zugelieferten Daten einen Modellierungsfehler gefunden und leite die Fragestellung entsprechend weiter.

**Comment by jendrikw** [comment]
Das Problem besteht mit Datensatz vom 30.03.2026 immer noch.

```
$ sha1sum 20260330_fahrplaene_gesamtdeutschland_gtfs.zip 
50fe62cd030ffc96f680a2f1287e94cf2d05ce1e  20260330_fahrplaene_gesamtdeutschland_gtfs.zip
```

```
$  rg 'de:06412:11511:91:91[^_][^G]'
transfers.txt
223237:"de:06412:2932","de:06412:11511:91:91",2,600,,,,
883367:"de:06412:11511:91:91","de:06412:2932",2,600,,,,
```
