### ISSUE TITLE
DELFI: Ungültige shape_id Referenzen

### ISSUE THREAD

**Issue by hbruch** [mfdz/GTFS-Issues#84]
**Beschreibe den Fehler**
Für 1296 trips ist der via shape_id referenzierte shape nicht in shapes.txt enthalten. 

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/2187389/144833429-2220579e-d7d4-4a92-80e1-f969e8c348fb.png">

**Referenz**
https://developers.google.com/transit/gtfs/reference/#tripstxt

**Aktualisierungszeitpunkt der GTFS-Daten:**
03.12.2021

**Downloadlink der GTFS-Daten:**
via https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View

**Comment by derhuerst** [comment]
Mit dem DELFI-Datensatz vom 21.03.2022 und [`gtfs-via-postgres`](https://www.npmjs.com/package/gtfs-via-postgres):

```sql
SELECT COUNT(*)
FROM (
	SELECT
		DISTINCT ON (trip_id)
		trip_id,
		routes.route_id, route_short_name,
		agency.agency_id, agency.agency_name
	FROM trips
	LEFT JOIN routes ON routes.route_id = trips.route_id
	LEFT JOIN agency ON agency.agency_id = routes.agency_id
	LEFT JOIN shapes ON shapes.shape_id = trips.shape_id
	WHERE shapes.shape_id IS NULL
) t
-- count
-- 0
```

**Comment by hbruch** [comment]
Fehler anscheinend beseitigt
