### ISSUE TITLE
MVV: Die "Münchner Verkehrsgesellschaft (MVG)" stellt GTFS bereit

### ISSUE THREAD

**Issue by osm-ToniE** [mfdz/GTFS-Issues#87]
**Beschreibe die Ergänzung/Erweiterung des Feeds, die Du wünscht**
Die Stadtbusse/-trams und U-Bahnen des MVV sind darin enthalten

**Aktualisierungszeitpunkt der GTFS-Daten:**
2022-03-10 ... in kurzen Abständen

**Downloadlink der GTFS-Daten:**
https://www.mvg.de/static/gtfs/gtfs-mvg.zip

**Lizenzhinweis:**
[Diese Informationen können z. B. von Routingdiensten oder interessierten Privatpersonen ausgelesen und verarbeitet werden.](https://www.mvg.de/services/fahrgastservice/fahrplandaten.html)

**Hinweis für OSM:**
[Freigabe durch die MVG für OSM: 'Die auf unserer Website bereitgestellten GFTS-Daten stehen Ihnen ohne Einschränkungen zur Verfügung, somit können Sie sie auch gerne für OSM nutzen.'](https://wiki.openstreetmap.org/wiki/DE:Permissions#ab_2021)

**Comment by hbruch** [comment]
In GTFS-Hub aufgenommen mit https://github.com/mfdz/gtfs-hub/commit/8ef718c143d8a46ec1a5e0f1b23632f5e1b370c7

@osm-ToniE Können wir den Eintrag hier damit schließen?

**Comment by osm-ToniE** [comment]
Ja, danke!

**Comment by osm-ToniE** [comment]
Die MVG ist auf https://gtfs.mfdz.de/ noch nicht sichtbar
