### ISSUE TITLE
Generell: Plausibilitätsprüfung bei PTNA

### ISSUE THREAD

**Issue by osm-ToniE** [mfdz/GTFS-Issues#88]
Bei PTNA wird versucht, folgende Fehler (?) zu erkennen:

* trips, die nur 2 Haltestellen haben, sind verdächtig
  * [z.B. MVV 221 Wendeanweisung an den Busfahrer](https://ptna.openstreetmap.de/gtfs/DE/single-trip.php?feed=DE-BY-MVV&release_date=2022-02-16&trip_id=100.T2.19-221-s22-3.2.R)
  * [z.B. MVV 210 Fahrt zum nächsten Einsatzort = Leerfahrt](https://ptna.openstreetmap.de/gtfs/DE/single-trip.php?feed=DE-BY-MVV&release_date=2022-02-16&trip_id=222.T0.19-210-s22-2.6.H)
* trips, bei denen die Namen der ersten und zweiten Haltestelle identisch sind, sind verdächtig
  * [z.B. VBB 101](https://ptna.openstreetmap.de/gtfs/DE/single-trip.php?feed=DE-BE-VBB&release_date=2022-03-04&trip_id=171690205) hier ist sogar lat/lon uns stop_id identisch
  * es gibt Ausnahmen! [z.B. MVV 221](https://ptna.openstreetmap.de/gtfs/DE/single-trip.php?feed=DE-BY-MVV&release_date=&trip_id=1.T2.19-221-s22-3.1.R)
* trips, bei denen die Namen der vorletzten und letzten Haltestelle identisch sind, sind verdächtig
  * [z.B. VBB 115](https://ptna.openstreetmap.de/gtfs/DE/single-trip.php?feed=DE-BE-VBB&release_date=2022-03-04&trip_id=171692931) ist das tatsächlich ein Fehler? 
  * es gibt Ausnahmen!

**Comment by hbruch** [comment]
Danke @osm-ToniE. Bei Punkt 1 (Trips mit nur zwei Haltestellen) kann ich mir eine Warnung vorstellen, wobei vermutlich in Abhängigkeit vom RouteType die Falsch-Positiv-Quote extrem hoch sein dürfte (2 Haltestellen wären für mich bei cable cars, funiculars und ferries erst mal plausibel). Gibt es eventuell weitere Indizien in diesem Zusammenhang?

Bei erstem/letzten Halt identisch zu Nachfolger/Vorgänger vermute ich per se auch viele Falsch-Positive, wie Du sie schon als Ausnahmen angeführt hast. Sie sollten explizit ausgenommen werden können, damit sie nicht immer wieder als Fehler gelistet werden und die Akzeptanz der Validierung gefährden...

**Comment by osm-ToniE** [comment]
- "2 Haltestellen" werte ich derzeit nur bei 'bus' aus. Bei Fähre, Stand-/Drahtseilbahn, ... kommt das wohl häufiger vor.

- Für jeden GTFS-feed habe ich einen [Satz von Shell-Scripten](https://github.com/osm-ToniE/gtfs-feeds/tree/master/DE/BY/MVV) und zwei CSV-Dateien (als SQL-Table)
  - einer davon macht ein [post-processing](https://github.com/osm-ToniE/gtfs-feeds/blob/master/DE/BY/MVV/post-process-ptna-sqlite.sh) auf der (fast) fertigen SQlite-DB und filtert (mir bekannte) false-positive wieder raus 
  - setzt (natürlich) irgendwie Orts-/Fahrplan-Kenntnisse voraus

**Comment by hbruch** [comment]
Hi @osm-ToniE, schaue mir gerade diesen Eintrag an. Die ursprüglichen Links sind mittlerweile anscheinend ungültig geworden. Ich würde daher diesen Issue entweder schließen oder magst Du ihn konkretisieren, indem du eine aktuelle Liste der Problemfälle anhängst, die dann auch adressiert werden können?

**Comment by osm-ToniE** [comment]
Hi @hbruch, ich denke du kannst diesen Issue schließen. Eine komplette Liste von Problemfällen habe ich eh nicht.

**Comment by hbruch** [comment]
Nähere Information zu ptna und seinen Möglichkeiten, Haltestellenabweichungen zwischen GTFS und OSM zu erkennen, erläutert @osm-ToniE in dieser [Aufzeichnung](https://meet.systect.de/playback/presentation/2.3/e611df5cf1e5c7d3be388c718baa518d97b5b6a7-1712577469733) des OpenTransport DataQualityMeetups vom 8.4.2024
