### ISSUE TITLE
VBB: stops mit "VERWAIST" im Namen

### ISSUE THREAD

**Issue by derhuerst** [mfdz/GTFS-Issues#98]
**Beschreibe den Fehler**

Einige stops enthalten den Präfix `VERWAIST: `, es existieren aber `stop_times` für diese:

```sql
SELECT
	DISTINCT ON (stops.stop_id)
	stops.stop_id, stops.stop_name, stops.zone_id,
	st_y(stops.stop_loc::geometry) as stop_lat, st_x(stops.stop_loc::geometry) as stop_lon,
	stops.location_type, stops.parent_station,
	COUNT(stop_times.stop_id) OVER (PARTITION BY stops.stop_id) nr_of_stop_times
FROM stops
LEFT JOIN stop_times ON stop_times.stop_id = stops.stop_id
WHERE stop_name LIKE '%VERWAIST%'
```

`stop_id` | `stop_name` | `zone_id` | `stop_lat` | `stop_lon` | `location_type` | `parent_station` | `nr_of_stop_times`
-|-|-|-|-|-|-|-
`de:12072:900245162::1` | `VERWAIST: Jüterbog, Wiesenhalle` | `6751 VERWAIST: Jüterbog, Wiesenhalle` | `51,993868` | `13,074586` | `stop` | `5`
`de:12072:900245162::2` | `VERWAIST: Jüterbog, Wiesenhalle` | `6751 VERWAIST: Jüterbog, Wiesenhalle` | `51,993875` | `13,07412` | `stop` | `7`
`de:12072:900245162::3` | `VERWAIST: Jüterbog, Wiesenhalle` | `6751 VERWAIST: Jüterbog, Wiesenhalle` | `51,993883` | `13,073725` | `stop` | `2`
`de:12072:900245162::4` | `VERWAIST: Jüterbog, Wiesenhalle` | `6751 VERWAIST: Jüterbog, Wiesenhalle` | `51,993825` | `13,07355` | `stop` | `8`

**Referenz**

zur Analyse verwendetes Tool: [`gtfs-via-postgres`](https://npmjs.com/package/gtfs-via-postgres)

**Aktualisierungszeitpunkt der GTFS-Daten:**

[2022-04-01](https://vbb-gtfs.jannisr.de/2022-04-01)

**Comment by derhuerst** [comment]
cc @OpenDataVBB

**Comment by OpenDataVBB** [comment]
@derhuerst Wird im kommenden Feed korrigiert.

**Comment by derhuerst** [comment]
Der aktuelle Feed enthält leider immer noch solche Haltestellen:

```shell
curl 'https://vbb-gtfs.jannisr.de/2022-11-25/stops.csv' -sfL | xsv search -s stop_name -i 'verwaist'
```

```
stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,platform_code,zone_id,level_id
de:12071:900446332::1,,"VERWAIST: Spremberg, Förderschule",Verwaist: Bushalt Slamener Höhe,51.571880000000,14.395809000000,0,,0,,"7671 VERWAIST: Spremberg, Förderschule",4
de:12070:900216017::1,,"VERWAIST: Weisen, Post",Bushalt Post,53.021379000000,11.785950000000,0,,0,,"4330 VERWAIST: Weisen, Post",9
de:12070:900216017::2,,"VERWAIST: Weisen, Post",Bushalt Post,53.021618000000,11.786294000000,0,,0,,"4330 VERWAIST: Weisen, Post",9
```

Gibt es automatisierte Vorkehrungen, wie etwa ein Validierungs-Script, die sicherstellen, dass dieser Fehler nicht wieder auftritt?

**Comment by OpenDataVBB** [comment]
Danke für den Hinweis.
Ab 11.12 haben die Fahrten wieder Verkehre, das VERWAIST wurde jetzt entfernt. Sollte mit dem heutigen/morgigen Updaten also korrigiert sein.
Ein Script zu dem Thema existiert meines Wissens nach nicht.
